In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize

In [2]:
x = np.array([[1, 100, 125], [2, 200, 275], [3, 300, 425]])
x

array([[  1, 100, 125],
       [  2, 200, 275],
       [  3, 300, 425]])

In [4]:
normalize(x, norm='l1', axis=1)

array([[0.00442478, 0.44247788, 0.55309735],
       [0.00419287, 0.41928721, 0.57651992],
       [0.00412088, 0.41208791, 0.58379121]])

In [5]:
normalize(x, norm='l2')

array([[0.00624683, 0.62468286, 0.78085357],
       [0.00588162, 0.58816152, 0.8087221 ],
       [0.00576674, 0.57667361, 0.81695428]])

In [ ]:
from sklearn.preprocessing import Normalizer
normalizer = Normalizer(norm='l2')
normalizer.transform(x)

array([[0.00624683, 0.62468286, 0.78085357],
       [0.00588162, 0.58816152, 0.8087221 ],
       [0.00576674, 0.57667361, 0.81695428]])

In [8]:
normalizer.fit(x)

Normalizer()

In [22]:
from ucimlrepo import fetch_ucirepo 

dataset = fetch_ucirepo(id=17)
X = dataset.data.features
Y = dataset.data.targets

In [23]:
X

,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,fractal_dimension1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [24]:
Y

    Diagnosis
0           M
1           M
2           M
3           M
4           M
..        ...
564         M
565         M
566         M
567         M
568         B

[569 rows x 1 columns]

In [25]:
X.replace(['?', 'na', 'nil', ' '], np.nan, inplace=True)
X.isna().sum()

C:\Users\aqdas\AppData\Local\Temp\ipykernel_8008\1718996473.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.replace(['?', 'na', 'nil', ' '], np.nan, inplace=True)

radius1               0
texture1              0
perimeter1            0
area1                 0
smoothness1           0
compactness1          0
concavity1            0
concave_points1       0
symmetry1             0
fractal_dimension1    0
radius2               0
texture2              0
perimeter2            0
area2                 0
smoothness2           0
compactness2          0
concavity2            0
concave_points2       0
symmetry2             0
fractal_dimension2    0
radius3               0
texture3              0
perimeter3            0
area3                 0
smoothness3           0
compactness3          0
concavity3            0
concave_points3       0
symmetry3             0
fractal_dimension3    0
dtype: int64

In [26]:
normalize(X, norm='l1', axis=0)

array([[0.002238  , 0.00094572, 0.00234663, ..., 0.00406987, 0.00278759,
        0.00248926],
       [0.00255896, 0.00161901, 0.00253963, ..., 0.00285228, 0.00166613,
        0.0018637 ],
       [0.00244948, 0.00193608, 0.00248422, ..., 0.00372637, 0.00218899,
        0.00183355],
       ...,
       [0.00206508, 0.00255835, 0.00206954, ..., 0.00217448, 0.00134381,
        0.00163718],
       [0.00256269, 0.00267224, 0.00267722, ..., 0.00406374, 0.00247617,
        0.00259603],
       [0.00096536, 0.00223583, 0.00091572, ..., 0.        , 0.00173944,
        0.00147367]], shape=(569, 30))