In [576]:
import pandas as pd
import numpy as np

In [577]:
df = pd.read_csv('insurance.csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [578]:
df.replace(['?', 'nan', ' ', 'nil'], np.nan, inplace=True)
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [579]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [580]:
df['charges'] = round(df.charges, 2)

In [581]:
df

      age     sex     bmi  children smoker     region   charges
0      19  female  27.900         0    yes  southwest  16884.92
1      18    male  33.770         1     no  southeast   1725.55
2      28    male  33.000         3     no  southeast   4449.46
3      33    male  22.705         0     no  northwest  21984.47
4      32    male  28.880         0     no  northwest   3866.86
...   ...     ...     ...       ...    ...        ...       ...
1333   50    male  30.970         3     no  northwest  10600.55
1334   18  female  31.920         0     no  northeast   2205.98
1335   18  female  36.850         0     no  southeast   1629.83
1336   21  female  25.800         0     no  southwest   2007.94
1337   61  female  29.070         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [582]:
X = df.drop('charges', axis=1)
Y = df['charges']

In [583]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y)

In [584]:
from sklearn.preprocessing import OneHotEncoder

In [585]:
one = OneHotEncoder(sparse_output=False, drop='first')

In [586]:
x_train_encoded = one.fit_transform(x_train.select_dtypes(include='object'))
x_test_encoded = one.transform(x_test.select_dtypes(include='object'))

In [587]:
x_train_encoded

array([[1., 1., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]], shape=(1003, 5))

In [588]:
x_train_encoded = pd.DataFrame(x_train_encoded, columns=one.get_feature_names_out())
x_test_encoded = pd.DataFrame(x_test_encoded, columns=one.get_feature_names_out())
x_train_encoded

,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,1.0,1.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...
998,0.0,0.0,0.0,1.0,0.0
999,1.0,1.0,0.0,0.0,1.0
1000,0.0,0.0,0.0,1.0,0.0
1001,1.0,0.0,0.0,0.0,1.0
1002,0.0,0.0,0.0,0.0,1.0

In [589]:
x_train = pd.concat([x_train.select_dtypes(exclude='object').reset_index(), x_train_encoded], axis=1)
x_test = pd.concat([x_test.select_dtypes(exclude='object').reset_index(), x_test_encoded], axis=1)

x_train.drop('index', axis=1, inplace=True)
x_test.drop('index', axis=1, inplace=True)

x_train

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,64,23.760,0,1.0,1.0,0.0,1.0,0.0
1,41,32.200,1,0.0,0.0,0.0,0.0,1.0
2,45,27.645,1,0.0,0.0,1.0,0.0,0.0
3,38,34.800,2,0.0,0.0,0.0,0.0,1.0
4,62,32.680,0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
998,64,35.970,0,0.0,0.0,0.0,1.0,0.0
999,43,27.800,0,1.0,1.0,0.0,0.0,1.0
1000,55,30.140,2,0.0,0.0,0.0,1.0,0.0
1001,58,38.000,0,1.0,0.0,0.0,0.0,1.0
1002,60,28.700,1,0.0,0.0,0.0,0.0,1.0

In [590]:
x_train.bmi.describe()

count    1003.000000
mean       30.809177
std         6.065770
min        16.815000
25%        26.600000
50%        30.495000
75%        34.930000
max        53.130000
Name: bmi, dtype: float64

In [591]:
y_train.dtype

dtype('float64')

In [592]:
from sklearn.preprocessing import StandardScaler
y_scaler = StandardScaler()

y_train_scaled = y_scaler.fit_transform(y_train.values.reshape(-1, 1))

In [593]:
y_train_scaled

array([[ 1.13706419e+00],
       [-5.33544729e-01],
       [ 1.25426726e+00],
       ...,
       [-1.10223984e-01],
       [-1.53005328e-01],
       [ 1.09605525e-03]], shape=(1003, 1))

In [594]:
y_train = pd.DataFrame(y_train_scaled, columns=['charges'])
y_train

       charges
0     1.137064
1    -0.533545
2     1.254267
3    -0.550492
4     0.052507
...        ...
998   0.091394
999   2.041010
1000 -0.110224
1001 -0.153005
1002  0.001096

[1003 rows x 1 columns]

In [595]:
y_test_scaled = y_scaler.transform(y_test.values.reshape(-1, 1))

In [596]:
import torch
from torch import nn
from torch.nn import functional as f

In [597]:
x_train_tensor = torch.tensor(x_train.values, dtype=torch.float32)
x_test_tensor = torch.tensor(x_test.values, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test_scaled, dtype=torch.float32)

In [598]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(in_features=8, out_features=1)

  def forward(self, x):
    return self.linear(x)

In [599]:
model = LinearRegressionModel()
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(params=model.parameters(), lr=0.0001)

In [600]:
#Training Loop
for i in range(100000):
  model.train()
  optimizer.zero_grad()
  output = model(x_train_tensor)
  loss = loss_fn(output, y_train_tensor)

  loss.backward()
  optimizer.step()

  if (i%10 == 0):
    print(f'Epoch[{i+1}/100000]', 'loss:', loss.item())

Epoch[1/100000] loss: 28.54949188232422
Epoch[11/100000] loss: 6.792728424072266
Epoch[21/100000] loss: 5.00358772277832
Epoch[31/100000] loss: 3.75742506980896
Epoch[41/100000] loss: 2.889415979385376
Epoch[51/100000] loss: 2.2847745418548584
Epoch[61/100000] loss: 1.863555669784546
Epoch[71/100000] loss: 1.570082187652588
Epoch[81/100000] loss: 1.365577220916748
Epoch[91/100000] loss: 1.223035454750061
Epoch[101/100000] loss: 1.1236475706100464
Epoch[111/100000] loss: 1.0543147325515747
Epoch[121/100000] loss: 1.0059139728546143
Epoch[131/100000] loss: 0.9720914959907532
Epoch[141/100000] loss: 0.9484219551086426
Epoch[151/100000] loss: 0.9318237900733948
Epoch[161/100000] loss: 0.9201505780220032
Epoch[171/100000] loss: 0.9119072556495667
Epoch[181/100000] loss: 0.9060530662536621
Epoch[191/100000] loss: 0.901862621307373
Epoch[201/100000] loss: 0.8988310694694519
Epoch[211/100000] loss: 0.8966069221496582
Epoch[221/100000] loss: 0.8949447870254517
Epoch[231/100000] loss: 0.893674373626709
Epoch[241/100000] loss: 0.892676830291748
Epoch[251/100000] loss: 0.8918695449829102
Epoch[261/100000] loss: 0.8911946415901184
Epoch[271/100000] loss: 0.8906121850013733
Epoch[281/100000] loss: 0.8900939226150513
Epoch[291/100000] loss: 0.8896207809448242
Epoch[301/100000] loss: 0.889178991317749
Epoch[311/100000] loss: 0.8887591361999512
Epoch[321/100000] loss: 0.8883545994758606
Epoch[331/100000] loss: 0.8879607915878296
Epoch[341/100000] loss: 0.8875747323036194
Epoch[351/100000] loss: 0.8871938586235046
Epoch[361/100000] loss: 0.8868169784545898
Epoch[371/100000] loss: 0.8864428400993347
Epoch[381/100000] loss: 0.8860706686973572
Epoch[391/100000] loss: 0.8856998682022095
Epoch[401/100000] loss: 0.885330319404602
Epoch[411/100000] loss: 0.8849615454673767
Epoch[421/100000] loss: 0.8845934271812439
Epoch[431/100000] loss: 0.8842259645462036
Epoch[441/100000] loss: 0.8838587999343872
Epoch[451/100000] loss: 0.8834922313690186
Epoch[461/100000] loss: 0.883125901222229
Epoch[471/100000] loss: 0.8827599287033081
Epoch[481/100000] loss: 0.8823943734169006
Epoch[491/100000] loss: 0.8820289373397827
Epoch[501/100000] loss: 0.8816638588905334
Epoch[511/100000] loss: 0.8812990784645081
Epoch[521/100000] loss: 0.8809347152709961
Epoch[531/100000] loss: 0.8805704116821289
Epoch[541/100000] loss: 0.8802065253257751
Epoch[551/100000] loss: 0.8798428177833557
Epoch[561/100000] loss: 0.8794794082641602
Epoch[571/100000] loss: 0.8791162967681885
Epoch[581/100000] loss: 0.8787534832954407
Epoch[591/100000] loss: 0.878390908241272
Epoch[601/100000] loss: 0.8780285716056824
Epoch[611/100000] loss: 0.8776665329933167
Epoch[621/100000] loss: 0.87730473279953
Epoch[631/100000] loss: 0.8769431710243225
Epoch[641/100000] loss: 0.8765820264816284
Epoch[651/100000] loss: 0.8762208819389343
Epoch[661/100000] loss: 0.8758602142333984
Epoch[671/100000] loss: 0.8754998445510864
Epoch[681/100000] loss: 0.875139594078064
Epoch[691/100000] loss: 0.8747796416282654
Epoch[701/100000] loss: 0.8744199275970459
Epoch[711/100000] loss: 0.8740606307983398
Epoch[721/100000] loss: 0.8737013936042786
Epoch[731/100000] loss: 0.8733425736427307
Epoch[741/100000] loss: 0.8729839324951172
Epoch[751/100000] loss: 0.872625470161438
Epoch[761/100000] loss: 0.872267484664917
Epoch[771/100000] loss: 0.8719096183776855
Epoch[781/100000] loss: 0.8715521097183228
Epoch[791/100000] loss: 0.8711948990821838
Epoch[801/100000] loss: 0.8708377480506897
Epoch[811/100000] loss: 0.8704809546470642
Epoch[821/100000] loss: 0.870124340057373
Epoch[831/100000] loss: 0.8697681427001953
Epoch[841/100000] loss: 0.8694121837615967
Epoch[851/100000] loss: 0.8690564036369324
Epoch[861/100000] loss: 0.8687008619308472
Epoch[871/100000] loss: 0.8683456182479858
Epoch[881/100000] loss: 0.8679906129837036
Epoch[891/100000] loss: 0.86763596534729
Epoch[901/100000] loss: 0.867281436920166
Epoch[911/100000] loss: 0.8669272661209106
Epoch[921/100000] loss: 0.8665733933448792
Epoch[931/100000] loss: 0.8662196397781372
Epoch[941/100000] loss: 0.8658661246299744
Epoch[951/100000] loss: 0.8655130863189697
Epoch[961/100000] loss: 0.8651601076126099
Epoch[971/100000] loss: 0.8648074865341187
Epoch[981/100000] loss: 0.8644550442695618
Epoch[991/100000] loss: 0.8641029000282288
Epoch[1001/100000] loss: 0.8637509346008301
Epoch[1011/100000] loss: 0.8633994460105896
Epoch[1021/100000] loss: 0.8630480170249939
Epoch[1031/100000] loss: 0.8626969456672668
Epoch[1041/100000] loss: 0.8623459935188293
Epoch[1051/100000] loss: 0.8619953989982605
Epoch[1061/100000] loss: 0.861644983291626
Epoch[1071/100000] loss: 0.8612948656082153
Epoch[1081/100000] loss: 0.8609450459480286
Epoch[1091/100000] loss: 0.8605954647064209
Epoch[1101/100000] loss: 0.8602460622787476
Epoch[1111/100000] loss: 0.8598970174789429
Epoch[1121/100000] loss: 0.8595482110977173
Epoch[1131/100000] loss: 0.859199583530426
Epoch[1141/100000] loss: 0.8588513731956482
Epoch[1151/100000] loss: 0.8585031628608704
Epoch[1161/100000] loss: 0.858155369758606
Epoch[1171/100000] loss: 0.8578079342842102
Epoch[1181/100000] loss: 0.8574605584144592
Epoch[1191/100000] loss: 0.8571134209632874
Epoch[1201/100000] loss: 0.8567665815353394
Epoch[1211/100000] loss: 0.85642009973526
Epoch[1221/100000] loss: 0.8560737371444702
Epoch[1231/100000] loss: 0.8557277321815491
Epoch[1241/100000] loss: 0.8553819060325623
Epoch[1251/100000] loss: 0.855036199092865
Epoch[1261/100000] loss: 0.8546909689903259
Epoch[1271/100000] loss: 0.8543459177017212
Epoch[1281/100000] loss: 0.854000985622406
Epoch[1291/100000] loss: 0.8536564707756042
Epoch[1301/100000] loss: 0.8533121347427368
Epoch[1311/100000] loss: 0.8529680967330933
Epoch[1321/100000] loss: 0.8526242971420288
Epoch[1331/100000] loss: 0.8522806763648987
Epoch[1341/100000] loss: 0.8519373536109924
Epoch[1351/100000] loss: 0.8515943884849548
Epoch[1361/100000] loss: 0.8512514233589172
Epoch[1371/100000] loss: 0.8509088754653931
Epoch[1381/100000] loss: 0.8505665063858032
Epoch[1391/100000] loss: 0.8502244353294373
Epoch[1401/100000] loss: 0.8498824834823608
Epoch[1411/100000] loss: 0.8495408892631531
Epoch[1421/100000] loss: 0.849199652671814
Epoch[1431/100000] loss: 0.8488584756851196
Epoch[1441/100000] loss: 0.8485175371170044
Epoch[1451/100000] loss: 0.8481769561767578
Epoch[1461/100000] loss: 0.8478366732597351
Epoch[1471/100000] loss: 0.8474963903427124
Epoch[1481/100000] loss: 0.8471564650535583
Epoch[1491/100000] loss: 0.8468168377876282
Epoch[1501/100000] loss: 0.8464775085449219
Epoch[1511/100000] loss: 0.8461382985115051
Epoch[1521/100000] loss: 0.8457993865013123
Epoch[1531/100000] loss: 0.8454607129096985
Epoch[1541/100000] loss: 0.845122218132019
Epoch[1551/100000] loss: 0.8447842001914978
Epoch[1561/100000] loss: 0.8444461822509766
Epoch[1571/100000] loss: 0.8441084623336792
Epoch[1581/100000] loss: 0.8437709808349609
Epoch[1591/100000] loss: 0.8434338569641113
Epoch[1601/100000] loss: 0.843096911907196
Epoch[1611/100000] loss: 0.8427601456642151
Epoch[1621/100000] loss: 0.8424237370491028
Epoch[1631/100000] loss: 0.84208744764328
Epoch[1641/100000] loss: 0.8417514562606812
Epoch[1651/100000] loss: 0.8414157032966614
Epoch[1661/100000] loss: 0.8410801291465759
Epoch[1671/100000] loss: 0.8407448530197144
Epoch[1681/100000] loss: 0.8404098749160767
Epoch[1691/100000] loss: 0.8400750160217285
Epoch[1701/100000] loss: 0.8397403359413147
Epoch[1711/100000] loss: 0.8394061326980591
Epoch[1721/100000] loss: 0.839072048664093
Epoch[1731/100000] loss: 0.838738203048706
Epoch[1741/100000] loss: 0.8384045958518982
Epoch[1751/100000] loss: 0.8380711674690247
Epoch[1761/100000] loss: 0.8377381563186646
Epoch[1771/100000] loss: 0.8374053239822388
Epoch[1781/100000] loss: 0.8370726108551025
Epoch[1791/100000] loss: 0.8367401361465454
Epoch[1801/100000] loss: 0.8364080190658569
Epoch[1811/100000] loss: 0.8360761404037476
Epoch[1821/100000] loss: 0.8357443809509277
Epoch[1831/100000] loss: 0.8354128003120422
Epoch[1841/100000] loss: 0.8350816369056702
Epoch[1851/100000] loss: 0.8347506523132324
Epoch[1861/100000] loss: 0.8344199061393738
Epoch[1871/100000] loss: 0.8340893387794495
Epoch[1881/100000] loss: 0.833759069442749
Epoch[1891/100000] loss: 0.8334290385246277
Epoch[1901/100000] loss: 0.8330991864204407
Epoch[1911/100000] loss: 0.8327696919441223
Epoch[1921/100000] loss: 0.8324403762817383
Epoch[1931/100000] loss: 0.8321112990379333
Epoch[1941/100000] loss: 0.8317822217941284
Epoch[1951/100000] loss: 0.8314536213874817
Epoch[1961/100000] loss: 0.8311252593994141
Epoch[1971/100000] loss: 0.8307970762252808
Epoch[1981/100000] loss: 0.8304691910743713
Epoch[1991/100000] loss: 0.8301414251327515
Epoch[2001/100000] loss: 0.8298140168190002
Epoch[2011/100000] loss: 0.8294868469238281
Epoch[2021/100000] loss: 0.8291597366333008
Epoch[2031/100000] loss: 0.8288329839706421
Epoch[2041/100000] loss: 0.828506350517273
Epoch[2051/100000] loss: 0.8281801342964172
Epoch[2061/100000] loss: 0.8278539776802063
Epoch[2071/100000] loss: 0.827528178691864
Epoch[2081/100000] loss: 0.827202558517456
Epoch[2091/100000] loss: 0.8268771767616272
Epoch[2101/100000] loss: 0.8265519738197327
Epoch[2111/100000] loss: 0.8262270092964172
Epoch[2121/100000] loss: 0.8259023427963257
Epoch[2131/100000] loss: 0.825577974319458
Epoch[2141/100000] loss: 0.8252536654472351
Epoch[2151/100000] loss: 0.8249296545982361
Epoch[2161/100000] loss: 0.8246060013771057
Epoch[2171/100000] loss: 0.8242824077606201
Epoch[2181/100000] loss: 0.8239591121673584
Epoch[2191/100000] loss: 0.8236360549926758
Epoch[2201/100000] loss: 0.8233131170272827
Epoch[2211/100000] loss: 0.8229905366897583
Epoch[2221/100000] loss: 0.8226681351661682
Epoch[2231/100000] loss: 0.822346031665802
Epoch[2241/100000] loss: 0.8220239877700806
Epoch[2251/100000] loss: 0.8217023611068726
Epoch[2261/100000] loss: 0.8213809132575989
Epoch[2271/100000] loss: 0.8210596442222595
Epoch[2281/100000] loss: 0.8207387328147888
Epoch[2291/100000] loss: 0.8204178214073181
Epoch[2301/100000] loss: 0.8200973272323608
Epoch[2311/100000] loss: 0.8197769522666931
Epoch[2321/100000] loss: 0.8194568753242493
Epoch[2331/100000] loss: 0.8191370368003845
Epoch[2341/100000] loss: 0.8188172578811646
Epoch[2351/100000] loss: 0.8184979557991028
Epoch[2361/100000] loss: 0.8181787133216858
Epoch[2371/100000] loss: 0.8178597092628479
Epoch[2381/100000] loss: 0.8175409436225891
Epoch[2391/100000] loss: 0.8172224164009094
Epoch[2401/100000] loss: 0.8169041275978088
Epoch[2411/100000] loss: 0.8165860176086426
Epoch[2421/100000] loss: 0.8162683248519897
Epoch[2431/100000] loss: 0.8159505128860474
Epoch[2441/100000] loss: 0.815633237361908
Epoch[2451/100000] loss: 0.8153159618377686
Epoch[2461/100000] loss: 0.8149990439414978
Epoch[2471/100000] loss: 0.8146823644638062
Epoch[2481/100000] loss: 0.814365804195404
Epoch[2491/100000] loss: 0.8140495419502258
Epoch[2501/100000] loss: 0.8137334585189819
Epoch[2511/100000] loss: 0.8134177327156067
Epoch[2521/100000] loss: 0.8131020665168762
Epoch[2531/100000] loss: 0.8127866387367249
Epoch[2541/100000] loss: 0.8124715089797974
Epoch[2551/100000] loss: 0.812156617641449
Epoch[2561/100000] loss: 0.8118417859077454
Epoch[2571/100000] loss: 0.8115273118019104
Epoch[2581/100000] loss: 0.8112130761146545
Epoch[2591/100000] loss: 0.8108989596366882
Epoch[2601/100000] loss: 0.8105851411819458
Epoch[2611/100000] loss: 0.8102715015411377
Epoch[2621/100000] loss: 0.8099581003189087
Epoch[2631/100000] loss: 0.8096449971199036
Epoch[2641/100000] loss: 0.8093320727348328
Epoch[2651/100000] loss: 0.8090192079544067
Epoch[2661/100000] loss: 0.8087066411972046
Epoch[2671/100000] loss: 0.8083944916725159
Epoch[2681/100000] loss: 0.8080823421478271
Epoch[2691/100000] loss: 0.8077706098556519
Epoch[2701/100000] loss: 0.8074589371681213
Epoch[2711/100000] loss: 0.8071474432945251
Epoch[2721/100000] loss: 0.8068363070487976
Epoch[2731/100000] loss: 0.8065253496170044
Epoch[2741/100000] loss: 0.8062146306037903
Epoch[2751/100000] loss: 0.8059040904045105
Epoch[2761/100000] loss: 0.805593729019165
Epoch[2771/100000] loss: 0.8052836656570435
Epoch[2781/100000] loss: 0.8049737215042114
Epoch[2791/100000] loss: 0.804664134979248
Epoch[2801/100000] loss: 0.8043547868728638
Epoch[2811/100000] loss: 0.8040454983711243
Epoch[2821/100000] loss: 0.8037365078926086
Epoch[2831/100000] loss: 0.8034277558326721
Epoch[2841/100000] loss: 0.8031191229820251
Epoch[2851/100000] loss: 0.8028108477592468
Epoch[2861/100000] loss: 0.8025026321411133
Epoch[2871/100000] loss: 0.8021947741508484
Epoch[2881/100000] loss: 0.8018870949745178
Epoch[2891/100000] loss: 0.8015796542167664
Epoch[2901/100000] loss: 0.8012723922729492
Epoch[2911/100000] loss: 0.8009652495384216
Epoch[2921/100000] loss: 0.8006585836410522
Epoch[2931/100000] loss: 0.8003517985343933
Epoch[2941/100000] loss: 0.8000454902648926
Epoch[2951/100000] loss: 0.7997392416000366
Epoch[2961/100000] loss: 0.7994332909584045
Epoch[2971/100000] loss: 0.7991275191307068
Epoch[2981/100000] loss: 0.7988219857215881
Epoch[2991/100000] loss: 0.7985166907310486
Epoch[3001/100000] loss: 0.7982115149497986
Epoch[3011/100000] loss: 0.7979066967964172
Epoch[3021/100000] loss: 0.7976019382476807
Epoch[3031/100000] loss: 0.7972974181175232
Epoch[3041/100000] loss: 0.7969932556152344
Epoch[3051/100000] loss: 0.7966892123222351
Epoch[3061/100000] loss: 0.7963853478431702
Epoch[3071/100000] loss: 0.7960817217826843
Epoch[3081/100000] loss: 0.7957783341407776
Epoch[3091/100000] loss: 0.7954751253128052
Epoch[3101/100000] loss: 0.7951720952987671
Epoch[3111/100000] loss: 0.7948693037033081
Epoch[3121/100000] loss: 0.7945668697357178
Epoch[3131/100000] loss: 0.7942644953727722
Epoch[3141/100000] loss: 0.7939623594284058
Epoch[3151/100000] loss: 0.7936604022979736
Epoch[3161/100000] loss: 0.7933586239814758
Epoch[3171/100000] loss: 0.7930572032928467
Epoch[3181/100000] loss: 0.7927559614181519
Epoch[3191/100000] loss: 0.7924547791481018
Epoch[3201/100000] loss: 0.7921539545059204
Epoch[3211/100000] loss: 0.7918533086776733
Epoch[3221/100000] loss: 0.7915529012680054
Epoch[3231/100000] loss: 0.7912526726722717
Epoch[3241/100000] loss: 0.7909525632858276
Epoch[3251/100000] loss: 0.7906528115272522
Epoch[3261/100000] loss: 0.7903530597686768
Epoch[3271/100000] loss: 0.7900537848472595
Epoch[3281/100000] loss: 0.7897545695304871
Epoch[3291/100000] loss: 0.7894555926322937
Epoch[3301/100000] loss: 0.7891567945480347
Epoch[3311/100000] loss: 0.7888582944869995
Epoch[3321/100000] loss: 0.7885599136352539
Epoch[3331/100000] loss: 0.7882616519927979
Epoch[3341/100000] loss: 0.7879638671875
Epoch[3351/100000] loss: 0.7876661419868469
Epoch[3361/100000] loss: 0.7873685359954834
Epoch[3371/100000] loss: 0.7870712280273438
Epoch[3381/100000] loss: 0.7867741584777832
Epoch[3391/100000] loss: 0.786477267742157
Epoch[3401/100000] loss: 0.7861804962158203
Epoch[3411/100000] loss: 0.7858839631080627
Epoch[3421/100000] loss: 0.7855877876281738
Epoch[3431/100000] loss: 0.7852917313575745
Epoch[3441/100000] loss: 0.7849957942962646
Epoch[3451/100000] loss: 0.7847002148628235
Epoch[3461/100000] loss: 0.7844047546386719
Epoch[3471/100000] loss: 0.7841095328330994
Epoch[3481/100000] loss: 0.7838144302368164
Epoch[3491/100000] loss: 0.7835196852684021
Epoch[3501/100000] loss: 0.7832251191139221
Epoch[3511/100000] loss: 0.7829306721687317
Epoch[3521/100000] loss: 0.7826364636421204
Epoch[3531/100000] loss: 0.7823424339294434
Epoch[3541/100000] loss: 0.7820487022399902
Epoch[3551/100000] loss: 0.7817550897598267
Epoch[3561/100000] loss: 0.7814617156982422
Epoch[3571/100000] loss: 0.781168520450592
Epoch[3581/100000] loss: 0.7808755040168762
Epoch[3591/100000] loss: 0.7805826663970947
Epoch[3601/100000] loss: 0.7802902460098267
Epoch[3611/100000] loss: 0.7799978256225586
Epoch[3621/100000] loss: 0.7797056436538696
Epoch[3631/100000] loss: 0.7794137001037598
Epoch[3641/100000] loss: 0.7791219353675842
Epoch[3651/100000] loss: 0.778830349445343
Epoch[3661/100000] loss: 0.7785390019416809
Epoch[3671/100000] loss: 0.7782478928565979
Epoch[3681/100000] loss: 0.7779569625854492
Epoch[3691/100000] loss: 0.7776662707328796
Epoch[3701/100000] loss: 0.7773756980895996
Epoch[3711/100000] loss: 0.7770853638648987
Epoch[3721/100000] loss: 0.7767952084541321
Epoch[3731/100000] loss: 0.7765054106712341
Epoch[3741/100000] loss: 0.7762155532836914
Epoch[3751/100000] loss: 0.7759259939193726
Epoch[3761/100000] loss: 0.7756367325782776
Epoch[3771/100000] loss: 0.7753475904464722
Epoch[3781/100000] loss: 0.7750586867332458
Epoch[3791/100000] loss: 0.7747699022293091
Epoch[3801/100000] loss: 0.774481475353241
Epoch[3811/100000] loss: 0.7741930484771729
Epoch[3821/100000] loss: 0.7739049792289734
Epoch[3831/100000] loss: 0.7736170887947083
Epoch[3841/100000] loss: 0.7733293175697327
Epoch[3851/100000] loss: 0.7730417847633362
Epoch[3861/100000] loss: 0.772754430770874
Epoch[3871/100000] loss: 0.7724673748016357
Epoch[3881/100000] loss: 0.7721803784370422
Epoch[3891/100000] loss: 0.7718937397003174
Epoch[3901/100000] loss: 0.7716071009635925
Epoch[3911/100000] loss: 0.7713209390640259
Epoch[3921/100000] loss: 0.7710347175598145
Epoch[3931/100000] loss: 0.7707487940788269
Epoch[3941/100000] loss: 0.7704630494117737
Epoch[3951/100000] loss: 0.7701775431632996
Epoch[3961/100000] loss: 0.769892156124115
Epoch[3971/100000] loss: 0.7696070671081543
Epoch[3981/100000] loss: 0.7693221569061279
Epoch[3991/100000] loss: 0.7690374255180359
Epoch[4001/100000] loss: 0.7687528729438782
Epoch[4011/100000] loss: 0.7684683799743652
Epoch[4021/100000] loss: 0.7681844234466553
Epoch[4031/100000] loss: 0.7679004073143005
Epoch[4041/100000] loss: 0.7676166296005249
Epoch[4051/100000] loss: 0.7673331499099731
Epoch[4061/100000] loss: 0.7670497894287109
Epoch[4071/100000] loss: 0.7667665481567383
Epoch[4081/100000] loss: 0.7664836049079895
Epoch[4091/100000] loss: 0.7662007808685303
Epoch[4101/100000] loss: 0.7659182548522949
Epoch[4111/100000] loss: 0.7656358480453491
Epoch[4121/100000] loss: 0.7653536796569824
Epoch[4131/100000] loss: 0.7650718092918396
Epoch[4141/100000] loss: 0.764789879322052
Epoch[4151/100000] loss: 0.7645083665847778
Epoch[4161/100000] loss: 0.7642269134521484
Epoch[4171/100000] loss: 0.7639456987380981
Epoch[4181/100000] loss: 0.763664722442627
Epoch[4191/100000] loss: 0.7633839249610901
Epoch[4201/100000] loss: 0.7631033062934875
Epoch[4211/100000] loss: 0.7628229856491089
Epoch[4221/100000] loss: 0.7625426650047302
Epoch[4231/100000] loss: 0.7622626423835754
Epoch[4241/100000] loss: 0.761982798576355
Epoch[4251/100000] loss: 0.7617031335830688
Epoch[4261/100000] loss: 0.7614237070083618
Epoch[4271/100000] loss: 0.7611444592475891
Epoch[4281/100000] loss: 0.7608653903007507
Epoch[4291/100000] loss: 0.7605865001678467
Epoch[4301/100000] loss: 0.760308027267456
Epoch[4311/100000] loss: 0.7600294351577759
Epoch[4321/100000] loss: 0.7597510814666748
Epoch[4331/100000] loss: 0.7594729065895081
Epoch[4341/100000] loss: 0.7591951489448547
Epoch[4351/100000] loss: 0.7589173316955566
Epoch[4361/100000] loss: 0.7586398720741272
Epoch[4371/100000] loss: 0.7583625316619873
Epoch[4381/100000] loss: 0.7580855488777161
Epoch[4391/100000] loss: 0.7578085064888
Epoch[4401/100000] loss: 0.7575317025184631
Epoch[4411/100000] loss: 0.7572551965713501
Epoch[4421/100000] loss: 0.7569787502288818
Epoch[4431/100000] loss: 0.7567026615142822
Epoch[4441/100000] loss: 0.7564266324043274
Epoch[4451/100000] loss: 0.7561507821083069
Epoch[4461/100000] loss: 0.7558752298355103
Epoch[4471/100000] loss: 0.755599856376648
Epoch[4481/100000] loss: 0.7553246021270752
Epoch[4491/100000] loss: 0.7550495266914368
Epoch[4501/100000] loss: 0.7547747492790222
Epoch[4511/100000] loss: 0.7545000910758972
Epoch[4521/100000] loss: 0.7542255520820618
Epoch[4531/100000] loss: 0.753951370716095
Epoch[4541/100000] loss: 0.7536771297454834
Epoch[4551/100000] loss: 0.7534033060073853
Epoch[4561/100000] loss: 0.7531296014785767
Epoch[4571/100000] loss: 0.7528560757637024

In [601]:
model.eval()
with torch.inference_mode():
  test_output = model(x_test_tensor)
  test_loss = loss_fn(test_output, y_test_tensor)

print(f'Test Loss: {test_loss.item()}')

Test Loss: 0.3411456346511841

In [602]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [603]:
y_pred_unscaled = y_scaler.inverse_transform(test_output.detach().numpy())
y_test_unscaled = y_scaler.inverse_transform(y_test_tensor.detach().numpy())

mae = mean_absolute_error(y_test_unscaled, y_pred_unscaled)
mse = mean_squared_error(y_test_unscaled, y_pred_unscaled)
r2 = r2_score(y_test_unscaled, y_pred_unscaled)

print(f'Mean Absolute Error (MAE): {mae:.2f}')
print(f'Mean Squared Error (MSE): {mse:.2f}')
print(f'R-squared (R2 Score): {r2:.2f}')

Mean Absolute Error (MAE): 4973.51
Mean Squared Error (MSE): 49632260.00
R-squared (R2 Score): 0.67